import type { GenrePreset } from "@track-forge/genre-core";
import type { HipHopInputs } from "./schema.js";

export const HIP_HOP_PRESETS: GenrePreset[] = [
  // ── Boom Bap ────────────────────────────────────────────────
  {
    id: "boom_bap_classic",
    name: "Boom Bap Classic",
    description: "Raw, gritty boom bap with hard drums and sampled loops",
    values: {
      subgenre: "boom_bap",
      bpm: 90,
      key: "D",
      scale: "minor",
      narrativeArc: "braggadocio",
      rhymeStyle: "multi_syllabic",
      flowPattern: "laid_back",
      delivery: "intense",
      productionStyle: "vintage",
      energy: 7,
      complexity: 7,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Trap ─────────────────────────────────────────────────────
  {
    id: "trap_banger",
    name: "Trap Banger",
    description: "Hard-hitting trap anthem with 808s and hi-hat rolls",
    values: {
      subgenre: "trap",
      bpm: 150,
      key: "F#",
      scale: "minor",
      narrativeArc: "braggadocio",
      rhymeStyle: "multi_syllabic",
      flowPattern: "syncopated",
      delivery: "hype",
      productionStyle: "polished",
      energy: 8,
      complexity: 5,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  {
    id: "trap_melodic",
    name: "Trap Melodic",
    description: "Melodic trap with sung hooks and atmospheric production",
    values: {
      subgenre: "trap",
      bpm: 140,
      key: "B",
      scale: "minor",
      narrativeArc: "introspective",
      rhymeStyle: "end_rhyme",
      flowPattern: "melodic",
      delivery: "conversational",
      productionStyle: "polished",
      energy: 6,
      complexity: 4,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Drill ────────────────────────────────────────────────────
  {
    id: "drill_aggressive",
    name: "Drill Aggressive",
    description: "Dark, aggressive drill with sliding 808s and raw delivery",
    values: {
      subgenre: "drill",
      bpm: 145,
      key: "C#",
      scale: "minor",
      narrativeArc: "braggadocio",
      rhymeStyle: "end_rhyme",
      flowPattern: "aggressive",
      delivery: "intense",
      productionStyle: "minimal",
      energy: 9,
      complexity: 5,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Old School ───────────────────────────────────────────────
  {
    id: "old_school_party",
    name: "Old School Party",
    description: "Classic breakbeat party rap with call-and-response energy",
    values: {
      subgenre: "old_school",
      bpm: 100,
      key: "A",
      scale: "major",
      narrativeArc: "party",
      rhymeStyle: "end_rhyme",
      flowPattern: "laid_back",
      delivery: "conversational",
      productionStyle: "vintage",
      energy: 8,
      complexity: 4,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Gangsta Rap ──────────────────────────────────────────────
  {
    id: "gangsta_story",
    name: "Gangsta Story",
    description:
      "Cinematic street narrative with heavy bass and raw storytelling",
    values: {
      subgenre: "gangsta_rap",
      bpm: 88,
      key: "E",
      scale: "minor",
      narrativeArc: "storytelling",
      rhymeStyle: "multi_syllabic",
      flowPattern: "laid_back",
      delivery: "intense",
      productionStyle: "vintage",
      energy: 7,
      complexity: 7,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── G-Funk ───────────────────────────────────────────────────
  {
    id: "g_funk_smooth",
    name: "G-Funk Smooth",
    description: "Laid-back G-Funk with P-funk synths and smooth delivery",
    values: {
      subgenre: "g_funk",
      bpm: 95,
      key: "G",
      scale: "major",
      narrativeArc: "braggadocio",
      rhymeStyle: "end_rhyme",
      flowPattern: "laid_back",
      delivery: "conversational",
      productionStyle: "vintage",
      energy: 5,
      complexity: 5,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── East Coast ───────────────────────────────────────────────
  {
    id: "east_coast_lyrical",
    name: "East Coast Lyrical",
    description: "Complex wordplay and dense lyricism over jazzy boom bap",
    values: {
      subgenre: "east_coast",
      bpm: 92,
      key: "D",
      scale: "minor",
      narrativeArc: "conscious",
      rhymeStyle: "internal",
      flowPattern: "syncopated",
      delivery: "intense",
      productionStyle: "vintage",
      energy: 7,
      complexity: 9,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Southern ─────────────────────────────────────────────────
  {
    id: "southern_slow",
    name: "Southern Slow",
    description: "Slow, heavy southern hip-hop with trunk-rattling bass",
    values: {
      subgenre: "southern_hip_hop",
      bpm: 78,
      key: "A",
      scale: "minor",
      narrativeArc: "braggadocio",
      rhymeStyle: "end_rhyme",
      flowPattern: "laid_back",
      delivery: "conversational",
      productionStyle: "polished",
      energy: 6,
      complexity: 4,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Crunk ────────────────────────────────────────────────────
  {
    id: "crunk_party",
    name: "Crunk Party",
    description: "High-energy crunk anthem with call-and-response hooks",
    values: {
      subgenre: "crunk",
      bpm: 80,
      key: "F",
      scale: "minor",
      narrativeArc: "party",
      rhymeStyle: "end_rhyme",
      flowPattern: "aggressive",
      delivery: "hype",
      productionStyle: "polished",
      energy: 10,
      complexity: 3,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Hyphy ────────────────────────────────────────────────────
  {
    id: "hyphy_turn_up",
    name: "Hyphy Turn Up",
    description: "Frenetic Bay Area hyphy with synth stabs and dance energy",
    values: {
      subgenre: "hyphy",
      bpm: 105,
      key: "A",
      scale: "major",
      narrativeArc: "party",
      rhymeStyle: "end_rhyme",
      flowPattern: "syncopated",
      delivery: "hype",
      productionStyle: "polished",
      energy: 9,
      complexity: 3,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Emo Rap ──────────────────────────────────────────────────
  {
    id: "emo_melancholy",
    name: "Emo Melancholy",
    description:
      "Emotional, introspective emo rap with rock-influenced melodies",
    values: {
      subgenre: "emo_rap",
      bpm: 160,
      key: "E",
      scale: "minor",
      narrativeArc: "introspective",
      rhymeStyle: "multi_syllabic",
      flowPattern: "melodic",
      delivery: "conversational",
      productionStyle: "polished",
      energy: 5,
      complexity: 6,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Lo-fi ────────────────────────────────────────────────────
  {
    id: "lo_fi_chill",
    name: "Lo-fi Chill",
    description: "Relaxed lo-fi hip-hop with vinyl crackle and jazz samples",
    values: {
      subgenre: "lo_fi_hip_hop",
      bpm: 80,
      key: "G",
      scale: "major",
      narrativeArc: "introspective",
      rhymeStyle: "multi_syllabic",
      flowPattern: "laid_back",
      delivery: "calm",
      productionStyle: "lo_fi",
      energy: 3,
      complexity: 5,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Jazz Rap ─────────────────────────────────────────────────
  {
    id: "jazz_rap_sophisticated",
    name: "Jazz Rap Sophisticated",
    description:
      "Intellectual jazz rap with live instrumentation and complex lyricism",
    values: {
      subgenre: "jazz_rap",
      bpm: 92,
      key: "D",
      scale: "major",
      narrativeArc: "conscious",
      rhymeStyle: "multi_syllabic",
      flowPattern: "syncopated",
      delivery: "conversational",
      productionStyle: "live_instruments",
      energy: 5,
      complexity: 9,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Conscious Rap ────────────────────────────────────────────
  {
    id: "conscious_message",
    name: "Conscious Message",
    description: "Thought-provoking conscious rap with socially aware lyrics",
    values: {
      subgenre: "conscious_rap",
      bpm: 92,
      key: "A",
      scale: "minor",
      narrativeArc: "conscious",
      rhymeStyle: "multi_syllabic",
      flowPattern: "laid_back",
      delivery: "conversational",
      productionStyle: "minimal",
      energy: 6,
      complexity: 8,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Alternative ──────────────────────────────────────────────
  {
    id: "alternative_experimental",
    name: "Alternative Experimental",
    description:
      "Genre-blending experimental hip-hop with non-traditional structures",
    values: {
      subgenre: "alternative_hip_hop",
      bpm: 95,
      key: "E",
      scale: "minor",
      narrativeArc: "abstract",
      rhymeStyle: "free_form",
      flowPattern: "syncopated",
      delivery: "conversational",
      productionStyle: "experimental",
      energy: 6,
      complexity: 8,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Phonk ────────────────────────────────────────────────────
  {
    id: "phonk_dark",
    name: "Phonk Dark",
    description: "Dark, lo-fi phonk with cowbells and Memphis-style delivery",
    values: {
      subgenre: "phonk",
      bpm: 76,
      key: "C#",
      scale: "minor",
      narrativeArc: "braggadocio",
      rhymeStyle: "end_rhyme",
      flowPattern: "laid_back",
      delivery: "intense",
      productionStyle: "lo_fi",
      energy: 7,
      complexity: 4,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── UK Drill ─────────────────────────────────────────────────
  {
    id: "uk_drill_street",
    name: "UK Drill Street",
    description: "Raw UK drill with slidey 808s and aggressive street delivery",
    values: {
      subgenre: "uk_drill",
      bpm: 145,
      key: "D",
      scale: "minor",
      narrativeArc: "braggadocio",
      rhymeStyle: "end_rhyme",
      flowPattern: "aggressive",
      delivery: "intense",
      productionStyle: "minimal",
      energy: 9,
      complexity: 5,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Grime ────────────────────────────────────────────────────
  {
    id: "grime_energetic",
    name: "Grime Energetic",
    description: "High-energy grime with synth stabs and breakneck delivery",
    values: {
      subgenre: "grime",
      bpm: 140,
      key: "F",
      scale: "minor",
      narrativeArc: "braggadocio",
      rhymeStyle: "multi_syllabic",
      flowPattern: "double_time",
      delivery: "intense",
      productionStyle: "electronic",
      energy: 9,
      complexity: 6,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Trap&B ───────────────────────────────────────────────────
  {
    id: "trap_b_romantic",
    name: "Trap&B Romantic",
    description:
      "Smooth trap&B with melodic rap-sung delivery and romantic themes",
    values: {
      subgenre: "trap_b",
      bpm: 130,
      key: "C",
      scale: "major",
      narrativeArc: "introspective",
      rhymeStyle: "multi_syllabic",
      flowPattern: "melodic",
      delivery: "conversational",
      productionStyle: "polished",
      energy: 5,
      complexity: 5,
      lyricsMode: "full_lyrics",
    } satisfies Partial<HipHopInputs>,
  },
  // ── Instrumental ─────────────────────────────────────────────
  {
    id: "hip_hop_instrumental",
    name: "Hip-Hop Instrumental",
    description: "Pure instrumental hip-hop beat",
    values: {
      subgenre: "boom_bap",
      bpm: 90,
      key: "C",
      scale: "minor",
      narrativeArc: "abstract",
      rhymeStyle: "end_rhyme",
      flowPattern: "laid_back",
      delivery: "conversational",
      productionStyle: "polished",
      energy: 5,
      complexity: 5,
      lyricsMode: "instrumental",
    } satisfies Partial<HipHopInputs>,
  },
];
