import type { GenrePreset } from "@track-forge/genre-core";
import type { EdmInputs } from "./schema.js";

export const EDM_PRESETS: GenrePreset[] = [
  {
    id: "deep_house_chill",
    name: "Deep House — Chill",
    description: "Warm, laid-back deep house with soulful chords",
    values: {
      family: "house",
      subgenre: "deep_house",
      bpm: 118,
      key: "auto",
      scale: "minor",
      mood: "warm and soulful",
      energy: 5,
      complexity: 4,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "tech_house_driving",
    name: "Tech House — Driving",
    description: "Loopy, driving tech house for the dancefloor",
    values: {
      family: "house",
      subgenre: "tech_house",
      bpm: 126,
      key: "auto",
      scale: "minor",
      mood: "driving and hypnotic",
      energy: 8,
      complexity: 5,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "progressive_house_euphoric",
    name: "Progressive House — Euphoric",
    description: "Building, euphoric progressive house with melodic peaks",
    values: {
      family: "house",
      subgenre: "progressive_house",
      bpm: 128,
      key: "auto",
      scale: "minor",
      mood: "euphoric and building",
      energy: 8,
      complexity: 7,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "detroit_techno_deep",
    name: "Detroit Techno — Deep",
    description: "Hypnotic, deep Detroit techno",
    values: {
      family: "techno",
      subgenre: "detroit_techno",
      bpm: 128,
      key: "auto",
      scale: "minor",
      mood: "deep and hypnotic",
      energy: 7,
      complexity: 6,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "industrial_techno_aggressive",
    name: "Industrial Techno — Aggressive",
    description: "Dark, aggressive industrial techno",
    values: {
      family: "techno",
      subgenre: "industrial_techno",
      bpm: 140,
      key: "auto",
      scale: "minor",
      mood: "dark and aggressive",
      energy: 9,
      complexity: 6,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "melodic_techno_emotional",
    name: "Melodic Techno — Emotional",
    description: "Emotional, atmospheric melodic techno",
    values: {
      family: "techno",
      subgenre: "melodic_techno",
      bpm: 124,
      key: "auto",
      scale: "minor",
      mood: "emotional and atmospheric",
      energy: 6,
      complexity: 7,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "uplifting_trance_anthem",
    name: "Uplifting Trance — Anthem",
    description: "Euphoric anthem trance with soaring leads",
    values: {
      family: "trance",
      subgenre: "uplifting_trance",
      bpm: 140,
      key: "auto",
      scale: "minor",
      mood: "euphoric and uplifting",
      energy: 9,
      complexity: 7,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "psytrance_trippy",
    name: "Psytrance — Trippy",
    description: "Fast, psychedelic trance with rolling bass",
    values: {
      family: "trance",
      subgenre: "psytrance",
      bpm: 145,
      key: "auto",
      scale: "minor",
      mood: "psychedelic and intense",
      energy: 9,
      complexity: 8,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "liquid_funk_soulful",
    name: "Liquid Funk — Soulful",
    description: "Melodic, soulful drum & bass",
    values: {
      family: "dnb",
      subgenre: "liquid_funk",
      bpm: 174,
      key: "auto",
      scale: "minor",
      mood: "soulful and melodic",
      energy: 7,
      complexity: 7,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "neurofunk_dark",
    name: "Neurofunk — Dark",
    description: "Dark, techy neurofunk with complex bass",
    values: {
      family: "dnb",
      subgenre: "neurofunk",
      bpm: 174,
      key: "auto",
      scale: "minor",
      mood: "dark and techy",
      energy: 8,
      complexity: 9,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "dubstep_heavy",
    name: "Dubstep — Heavy",
    description: "Massive dubstep with heavy wobble bass",
    values: {
      family: "bass",
      subgenre: "dubstep",
      bpm: 140,
      key: "auto",
      scale: "minor",
      mood: "dark and massive",
      energy: 9,
      complexity: 6,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "future_bass_bright",
    name: "Future Bass — Bright",
    description: "Bright, melodic future bass with emotional chords",
    values: {
      family: "bass",
      subgenre: "future_bass",
      bpm: 145,
      key: "auto",
      scale: "major",
      mood: "bright and emotional",
      energy: 7,
      complexity: 6,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "hardstyle_anthem",
    name: "Hardstyle — Anthem",
    description: "Hard-hitting euphoric hardstyle",
    values: {
      family: "hardcore",
      subgenre: "hardstyle",
      bpm: 150,
      key: "auto",
      scale: "minor",
      mood: "hard and euphoric",
      energy: 10,
      complexity: 6,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "chillout_relaxed",
    name: "Chillout — Relaxed",
    description: "Warm, relaxed ambient downtempo",
    values: {
      family: "downtempo",
      subgenre: "chillout",
      bpm: 90,
      key: "auto",
      scale: "major",
      mood: "relaxed and warm",
      energy: 3,
      complexity: 3,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "lo_fi_chilled",
    name: "Lo-Fi — Chilled",
    description: "Warm, dusty lo-fi beats",
    values: {
      family: "downtempo",
      subgenre: "lo_fi_beats",
      bpm: 80,
      key: "auto",
      scale: "major",
      mood: "chilled and nostalgic",
      energy: 3,
      complexity: 3,
      lyricsMode: "guided_instrumental",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "dance_pop_catchy",
    name: "Dance-Pop — Catchy",
    description: "Upbeat, radio-friendly dance-pop",
    values: {
      family: "pop",
      subgenre: "dance_pop",
      bpm: 118,
      key: "auto",
      scale: "major",
      mood: "catchy and upbeat",
      energy: 7,
      complexity: 4,
      lyricsMode: "full_lyrics",
    } satisfies Partial<EdmInputs>,
  },
  {
    id: "nu_disco_funky",
    name: "Nu-Disco — Funky",
    description: "Funky, disco-inspired dance pop",
    values: {
      family: "pop",
      subgenre: "nu_disco",
      bpm: 118,
      key: "auto",
      scale: "major",
      mood: "funky and uplifting",
      energy: 7,
      complexity: 5,
      lyricsMode: "full_lyrics",
    } satisfies Partial<EdmInputs>,
  },
];
